# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: white_arm
  joint_model_group_pose: write_position
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - black1_joint
    - black2_joint
    - black3_joint
    - black4_joint
    - black5_joint
    - black6_joint
    - black7_joint
    - BLink1
    - BLink11
    - BLink2
    - BLink22
    - BLink3
    - BLink33
    - BLink4
    - BLink44
    - BLink5
    - BLink51
    - BLink52
    - BLink53
    - neck1_joint
    - neck2_joint
    - white_joint1
    - white_joint2
    - white_joint3
    - white_joint4
    - white_joint5
    - Link3
    - Link33
    - Link4
    - Link44
    - Link5
    - Link51
    - Link52
    - Link53
    - white_finger_joint1
    - Link11
    - Link22
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []