aisr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  white1_controller:
    type: position_controllers/JointPositionController
    joint: white1_joint
    pid: {p: 2400.0, d: 18.0, i: 800.0, i_clamp: 4.0}

  white2_controller:
    type: position_controllers/JointPositionController
    joint: white2_joint
    pid: {p: 1200.0, d: 10.0, i: 700.0, i_clamp: 4.0}

  white3_controller:
    type: position_controllers/JointPositionController
    joint: white3_joint
    pid: {p: 1000.0, d: 6.0, i: 600.0, i_clamp: 4.0}

  white4_controller:
    type: position_controllers/JointPositionController
    joint: white4_joint
    pid: {p: 700.0, d: 4.0, i: 450, i_clamp: 4.0}

  white5_controller:
    type: position_controllers/JointPositionController
    joint: white5_joint
    pid: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}

  black1_controller:
    type: position_controllers/JointPositionController
    joint: black1_joint
    pid: {p: 2400.0, d: 18.0, i: 800.0, i_clamp: 4.0}

  black2_controller:
    type: position_controllers/JointPositionController
    joint: black2_joint
    pid: {p: 1200.0, d: 10.0, i: 700.0, i_clamp: 4.0}

  black3_controller:
    type: position_controllers/JointPositionController
    joint: black3_joint
    pid: {p: 1000.0, d: 6.0, i: 600.0, i_clamp: 4.0}

  black4_controller:
    type: position_controllers/JointPositionController
    joint: black4_joint
    pid: {p: 700.0, d: 4.0, i: 450, i_clamp: 4.0}

  black5_controller:
    type: position_controllers/JointPositionController
    joint: black5_joint
    pid: {p: 700.0, d: 4.0, i: 450, i_clamp: 4.0}

  black6_controller:
    type: position_controllers/JointPositionController
    joint: black6_joint
    pid: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}

  black7_controller:
    type: position_controllers/JointPositionController
    joint: black7_joint
    pid: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}

  waist1_controller:
    type: position_controllers/JointPositionController
    joint: waist1_joint
    pid: {p: 12000.0, d: 180.0, i: 60.0, i_clamp: 4.0}

  waist2_controller:
    type: position_controllers/JointPositionController
    joint: waist2_joint
    pid: {p: 6000.0, d: 1000.0, i: 30.0, i_clamp: 4.0}

  waist3_controller:
    type: position_controllers/JointPositionController
    joint: waist3_joint
    pid: {p: 6000.0, d: 1000.0, i: 30.0, i_clamp: 4.0}

  neck1_controller:
    type: position_controllers/JointPositionController
    joint: neck1_joint
    pid: {p: 250.0, d: 20.0, i: 2.0, i_clamp: 0.5}

  neck2_controller:
    type: position_controllers/JointPositionController
    joint: neck2_joint
    pid: {p: 80.0, d: 20.0, i: 1.6, i_clamp: 0.1}