controller_joint_names: ['', 'waist1', 'waist2', 'waist3', 'neck1', 'neck2', 'white1', 'white2', 'white3', 'white4', 'white5', 'black1', 'black2', 'black3', 'black4', 'black5', 'black6', 'black7', ]
